// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace YandexTrackerApi.DbModels;

public partial class CalendarDatum
{
    [Key]
    public DateOnly Day { get; set; }

    public bool Holiday { get; set; }

    public bool Short { get; set; }
}