// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace YandexTrackerApi.DbModels;

[Table("Diagram")]
public partial class Diagram
{
    [Key]
    public Guid Id { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string Name { get; set; }

    [Column(TypeName = "xml")]
    public string XmlDiagram { get; set; }

    [Column("Project_Id")]
    public Guid? ProjectId { get; set; }

    [ForeignKey("ProjectId")]
    [InverseProperty("Diagrams")]
    public virtual Project Project { get; set; }
}