// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace YandexTrackerApi.DbModels;

[Table("Project")]
public partial class Project
{
    [Key]
    public Guid Id { get; set; }

    [Required]
    [StringLength(255)]
    public string Name { get; set; }

    [StringLength(255)]
    public string Description { get; set; }

    public Guid CreatorId { get; set; }

    [InverseProperty("Project")]
    public virtual ICollection<Diagram> Diagrams { get; set; } = new List<Diagram>();

    [InverseProperty("Project")]
    public virtual ICollection<UsersProject> UsersProjects { get; set; } = new List<UsersProject>();

    [InverseProperty("IdNavigation")]
    public virtual YandexTracker YandexTracker { get; set; }

    [InverseProperty("Project")]
    public virtual ICollection<YandexTrackerUser> YandexTrackerUsers { get; set; } = new List<YandexTrackerUser>();
}