// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace YandexTrackerApi.DbModels;

[Keyless]
[Table("TaskHandlerMapping")]
public partial class TaskHandlerMapping
{
    public Guid? Id { get; set; }

    [StringLength(255)]
    public string NodeName { get; set; }

    [StringLength(255)]
    public string HandlerClassName { get; set; }

    [StringLength(255)]
    public string Description { get; set; }
}