// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace YandexTrackerApi.DbModels;

[Table("YandexTrackerTask")]
public partial class YandexTrackerTask
{
    [Key]
    [StringLength(255)]
    public string Id { get; set; }

    [StringLength(255)]
    public string Summary { get; set; }

    public int? OriginalEstimation { get; set; }

    public int? SpentTime { get; set; }

    [Column("User_Id")]
    [StringLength(255)]
    public string UserId { get; set; }

    public DateOnly? StartDate { get; set; }

    public DateOnly? EndDate { get; set; }

    [ForeignKey("UserId")]
    [InverseProperty("YandexTrackerTasks")]
    public virtual YandexTrackerUser User { get; set; }
}