// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace YandexTrackerApi.DbModels;

[Table("YandexTracker")]
public partial class YandexTracker
{
    [Key]
    public Guid Id { get; set; }

    [Column("OAuthToken")]
    [StringLength(255)]
    public string OauthToken { get; set; }

    [StringLength(255)]
    public string CloudOrgId { get; set; }

    [ForeignKey("Id")]
    [InverseProperty("YandexTracker")]
    public virtual Project IdNavigation { get; set; }
}