// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace YandexTrackerApi.DbModels;

[Table("YandexTrackerUser")]
public partial class YandexTrackerUser
{
    [Key]
    public Guid Id { get; set; }

    [StringLength(255)]
    public string Login { get; set; }

    [StringLength(255)]
    public string Name { get; set; }

    [Column("Project_Id")]
    public Guid? ProjectId { get; set; }

    [ForeignKey("ProjectId")]
    [InverseProperty("YandexTrackerUsers")]
    public virtual Project Project { get; set; }

    [InverseProperty("User")]
    public virtual ICollection<YandexTrackerUserHoliday> YandexTrackerUserHolidays { get; set; } = new List<YandexTrackerUserHoliday>();
}