// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace YandexTrackerApi.DbModels;

[Table("YandexTrackerUserHoliday")]
public partial class YandexTrackerUserHoliday
{
    [Key]
    public DateOnly Day { get; set; }

    [Column("User_Id")]
    public Guid? UserId { get; set; }

    [ForeignKey("UserId")]
    [InverseProperty("YandexTrackerUserHolidays")]
    public virtual YandexTrackerUser User { get; set; }
}