// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace BPMNWorkFlow.DbModels;

public partial class GraduateWorkContext : DbContext
{
    public GraduateWorkContext()
    {
    }

    public GraduateWorkContext(DbContextOptions<GraduateWorkContext> options)
        : base(options)
    {
    }

    public virtual DbSet<TaskHandlerMapping> TaskHandlerMappings { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see https://go.microsoft.com/fwlink/?LinkId=723263.
        => optionsBuilder.UseSqlServer("Data Source=LAPTOP-UJ3H26AC\\SQLEXPRESS;Initial Catalog=GraduateWork;Integrated Security=True;Encrypt=True");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<TaskHandlerMapping>(entity =>
        {
            entity
                .HasNoKey()
                .ToTable("TaskHandlerMapping");

            entity.Property(e => e.HandlerClassName).HasMaxLength(255);
            entity.Property(e => e.NodeName).HasMaxLength(255);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}