// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BPMNWorkFlow.DbModels;

public partial class TaskHandlerMapping
{
    public Guid Id { get; set; }

    public string NodeName { get; set; }

    public string HandlerClassName { get; set; }

    public Guid? NodeTypeId { get; set; }

    public virtual NodeType NodeType { get; set; }
}